version: '2'
services:
    naristi-cassandra:
        container_name: naristi-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/naristi/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    naristi-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: naristi-cassandra-migration
        links:
            - naristi-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
