version: '2'
services:
    naristi-mongodb:
        container_name: naristi-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/naristi/mongodb/:/data/db/
